// =====================================================================
//  Terms of Service page (/terms-of-service)
// =====================================================================
import { CONTACT_EMAIL } from "../../constants"

export const TermsPage = () => (
  <main className="legal-page">
    <div className="container legal-layout">
      <aside className="legal-sidebar">
        <nav className="legal-nav" aria-label="Legal pages">
          <a href="/terms-of-service" className="active">
            Terms of Service
          </a>
          <a href="/privacy-policy">Privacy Policy</a>
        </nav>
      </aside>

      <article className="legal-content">
        <h1>Terms of Service</h1>
        <p className="legal-meta">Last updated May 24, 2026</p>

        <p>
          Welcome, and thank you for your interest in Chunky Tofu Studios, LLC (
          <strong>"Chunky Tofu Studios,"</strong> <strong>"we,"</strong> or{" "}
          <strong>"us"</strong>), makers of the Ube software platform. These
          Terms of Service (<strong>"Terms"</strong>) govern your access to and
          use of our software, platform, APIs, documentation, and related tools,
          including the website <a href="https://ube.dev">ube.dev</a> and all
          related software made available by Chunky Tofu Studios to maintain,
          build, deploy, host, and manage software projects (collectively, the{" "}
          <strong>"Service"</strong>). By using the Service, you agree to these
          Terms.
        </p>

        <p>
          Please also read our <a href="/privacy-policy">Privacy Policy</a>,
          which explains how we collect, use, disclose, and process personal
          data.
        </p>

        <p>
          If you are using the Service as part of your work for a company or
          organization that has a Master Services Agreement (
          <strong>"MSA"</strong>) with Chunky Tofu Studios, your use of the
          Service is governed by that MSA.
        </p>

        <p>
          If you are entering into these Terms on behalf of an entity, you
          represent that you have the legal authority to bind that entity.
        </p>

        <h2 id="access">1. Access and Use</h2>

        <p>
          <strong>1.1. Provision of Access.</strong> Chunky Tofu Studios is an
          applied research company working on autonomous software maintenance.
          The Service offers a suite of agentic coding tools driven by machine
          learning that listen to crash feeds, error dashboards, app reviews,
          and dependency releases, and that triage, reproduce, and propose fixes
          against your repositories. Subject to your compliance with these
          Terms, Chunky Tofu Studios grants you a limited, non-exclusive,
          non-transferable, non-sublicensable, and revocable right to access and
          use the Service for your internal business or personal use.
        </p>

        <p>
          <strong>1.2. Beta and Early Access.</strong> Portions of the Service
          may be designated as alpha, beta, preview, early access, or
          experimental (<strong>"Beta Services"</strong>). Beta Services are
          provided "as-is" for evaluation purposes and may be discontinued,
          modified, or made generally available at our discretion. Beta Services
          may not be supported, may contain bugs or errors, may produce
          unexpected results, and may be subject to additional terms. Your use
          of Beta Services is at your sole risk.
        </p>

        <p>
          <strong>1.3. Inputs, Outputs, and Suggestions.</strong> The Service
          accepts content you provide or that the Service collects on your
          behalf — including source code, repository contents, crash reports,
          user feedback, configuration data, and prompts (collectively,{" "}
          <strong>"Inputs"</strong>) — and generates outputs such as proposed
          code changes, pull requests, summaries, and other materials
          (collectively, <strong>"Suggestions"</strong>). You authorize us to
          use Inputs and Suggestions as necessary to operate, maintain, and
          improve the Service.
        </p>

        <p>
          <strong>1.4. No Training on Your Content.</strong> We do not use
          Inputs or Suggestions to train our or any third party's machine
          learning models, unless: (1) they are flagged for security or abuse
          review (in which case we may analyze them to detect and enforce these
          Terms); (2) you explicitly report them to us (for example, as
          Feedback); or (3) you have explicitly agreed to such use.
        </p>

        <p>
          <strong>1.5. Limitations of AI Suggestions.</strong> Suggestions
          generated by the Service are produced by machine learning systems and
          may be inaccurate, incomplete, biased, or otherwise inappropriate. You
          are responsible for reviewing all Suggestions before merging,
          deploying, or otherwise acting on them. The Service is not a
          substitute for human judgment, professional code review, security
          testing, or legal advice. We make no representation that Suggestions
          are correct, secure, or fit for any particular purpose.
        </p>

        <p>
          <strong>1.6. Restrictions.</strong> You may not (and may not permit
          anyone else to): (a) reverse engineer, decompile, or attempt to derive
          the source code, models, or underlying algorithms of the Service
          except to the extent applicable law expressly permits; (b) use the
          Service to develop, train, or improve any competing machine learning
          model or product; (c) scrape, harvest, or otherwise collect data from
          the Service except through documented interfaces; (d) circumvent or
          attempt to circumvent rate limits, access controls, or security
          measures; (e) use the Service to infringe any intellectual property,
          privacy, or other right of any third party; (f) use the Service to
          transmit malware or other malicious code, or to engage in unlawful,
          harassing, or harmful conduct; or (g) use the Service in violation of
          any applicable law or regulation.
        </p>

        <p>
          <strong>1.7. Automated Execution.</strong> Where the Service executes
          commands, runs code, or takes other automated actions on your behalf
          (for example, opening pull requests, running tests, or interacting
          with third-party systems you have connected), you authorize those
          actions and accept full responsibility for their consequences. You are
          responsible for configuring appropriate branch protections, review
          requirements, sandboxing, and other guardrails. We are not liable for
          losses arising from automated actions you have authorized.
        </p>

        <h2 id="eligibility">2. Eligibility</h2>

        <p>
          You must be at least 18 years old (or the age of majority in your
          jurisdiction, whichever is greater) and have the legal capacity to
          enter into these Terms. You also represent that you have not been
          previously suspended or removed from the Service and that your use of
          the Service does not violate any agreement, law, or regulation
          applicable to you.
        </p>

        <h2 id="accounts">3. Account Registration and Access</h2>

        <p>
          Access to certain features may require an account. You agree to
          provide accurate, current, and complete information when registering,
          and to keep your information up to date. You are responsible for
          safeguarding your credentials and for all activities that occur under
          your account. Notify us promptly at{" "}
          <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a> if you suspect
          unauthorized access. We may refuse, suspend, or revoke access at any
          time.
        </p>

        <h2 id="payment">4. Payment Terms</h2>

        <p>
          <strong>4.1. Fees.</strong> Certain features of the Service may
          require payment of fees (<strong>"Fees"</strong>). Fees are described
          on the relevant order form, pricing page, or subscription page (
          <strong>"Order Form"</strong>). All Fees are non-refundable except as
          required by applicable law or as expressly stated in these Terms or
          your Order Form.
        </p>

        <p>
          <strong>4.2. Pricing Changes.</strong> We reserve the right to change
          pricing. Where required by your subscription tier, we will provide
          reasonable advance notice of pricing changes that affect you.
          Continued use of the Service after a pricing change takes effect
          constitutes acceptance of the new pricing.
        </p>

        <p>
          <strong>4.3. Payment Processing.</strong> Payments are processed by
          third-party payment processors. By providing payment information, you
          authorize us and our payment processors to charge the applicable Fees
          and any associated taxes to your selected payment method.
        </p>

        <p>
          <strong>4.4. Subscriptions and Renewals.</strong> Subscriptions
          automatically renew at the end of each billing period unless cancelled
          in accordance with the cancellation instructions provided in your
          account or Order Form. You are responsible for cancelling before the
          renewal date to avoid being charged for the next period.
        </p>

        <p>
          <strong>4.5. Taxes.</strong> Fees are exclusive of all applicable
          taxes, duties, and similar governmental charges, which are your
          responsibility unless we are required by law to collect them.
        </p>

        <p>
          <strong>4.6. Non-Payment.</strong> If your payment fails or your
          account is overdue, we may suspend or terminate your access to paid
          features of the Service. You remain liable for unpaid Fees and any
          reasonable costs of collection.
        </p>

        <h2 id="ownership">5. Ownership and Licenses</h2>

        <p>
          <strong>5.1. Our Intellectual Property.</strong> The Service,
          including all software, models, designs, text, graphics, logos, and
          other content (excluding Inputs and Suggestions you own under Section
          5.3) is owned by Chunky Tofu Studios or its licensors and is protected
          by intellectual property and other laws. Except for the limited rights
          expressly granted in these Terms, no rights are granted to you.
        </p>

        <p>
          <strong>5.2. Feedback.</strong> If you provide us with feedback,
          ideas, suggestions, or other information about the Service (
          <strong>"Feedback"</strong>), you grant us a perpetual, irrevocable,
          worldwide, royalty-free, sublicensable license to use Feedback for any
          purpose without compensation or attribution to you.
        </p>

        <p>
          <strong>5.3. Your Inputs and Suggestions.</strong> As between you and
          us, you retain all rights you have in your Inputs. Subject to your
          compliance with these Terms, we assign to you all rights we may have
          in the Suggestions generated for you, to the extent those rights are
          assignable. You are solely responsible for ensuring that you have the
          rights necessary to provide your Inputs and to use the Suggestions.
        </p>

        <p>
          <strong>5.4. Usage Data.</strong> We may collect and use aggregated,
          anonymized, or de-identified data about use of the Service (
          <strong>"Usage Data"</strong>) for any lawful business purpose,
          including improving the Service. Usage Data does not include the
          content of your Inputs or Suggestions in identifiable form.
        </p>

        <h2 id="third-parties">6. Third-Party Services</h2>

        <p>
          The Service may integrate with or rely on third-party products,
          services, or content (<strong>"Third-Party Services"</strong>),
          including repository hosts, dependency registries, crash reporting
          tools, and authentication providers. Third-Party Services are governed
          by their own terms and privacy policies. We do not control and are not
          responsible for Third-Party Services or the consequences of their use.
          Your interactions with Third-Party Services are solely between you and
          the provider.
        </p>

        <h2 id="communications">7. Communications</h2>

        <p>
          By using the Service, you agree to receive communications from us
          related to your account and the Service, including transactional
          messages and notices. We may also send you product updates,
          announcements, or other marketing communications. You may opt out of
          marketing communications by following the unsubscribe instructions in
          those messages. Opting out of marketing communications does not opt
          you out of essential, transactional messages.
        </p>

        <h2 id="changes">8. Modifications to These Terms</h2>

        <p>
          We may update these Terms from time to time. If we make material
          changes, we will provide reasonable notice (for example, by posting a
          notice on the Service or sending you an email). Changes take effect on
          the effective date stated at the top of the Terms. Your continued use
          of the Service after the effective date constitutes acceptance of the
          updated Terms. If you do not agree, you must stop using the Service.
        </p>

        <h2 id="termination">9. Termination</h2>

        <p>
          You may stop using the Service at any time. We may suspend or
          terminate your access to the Service, in whole or in part, at any time
          and for any reason, including if we believe you have violated these
          Terms. Upon termination, your right to access and use the Service
          ends. Sections that by their nature should survive termination —
          including Sections 1.5, 1.6, 4, 5, 11, 12, and 13–17 — will survive.
        </p>

        <h2 id="service-changes">10. Modifications to the Service</h2>

        <p>
          We may modify, suspend, or discontinue the Service, or any feature of
          the Service, at any time. We are not liable to you or any third party
          for any modification, suspension, or discontinuation of the Service.
        </p>

        <h2 id="copyright">11. Copyright Complaints</h2>

        <p>
          We respect the intellectual property rights of others. If you believe
          that material on the Service infringes your copyright, please send a
          notice to <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a> that
          includes: (a) a physical or electronic signature of the copyright
          owner or person authorized to act on their behalf; (b) identification
          of the copyrighted work claimed to have been infringed; (c)
          identification of the material claimed to be infringing, with
          information sufficient to locate it; (d) your contact information; (e)
          a statement that you have a good faith belief that the use is not
          authorized; and (f) a statement, made under penalty of perjury, that
          the information in the notice is accurate and that you are authorized
          to act on behalf of the copyright owner.
        </p>

        <h2 id="privacy">12. Privacy</h2>

        <p>
          Our <a href="/privacy-policy">Privacy Policy</a> describes how we
          collect, use, disclose, and process personal data in connection with
          the Service. By using the Service, you acknowledge that you have read
          and understood our Privacy Policy.
        </p>

        <h2 id="indemnity">13. Indemnity</h2>

        <p>
          To the maximum extent permitted by law, you agree to indemnify,
          defend, and hold harmless Chunky Tofu Studios and its officers,
          directors, employees, contractors, agents, and licensors from and
          against any claims, damages, losses, liabilities, costs, and expenses
          (including reasonable attorneys' fees) arising out of or relating to:
          (a) your use of the Service; (b) your Inputs or actions taken in
          reliance on Suggestions; (c) your violation of these Terms; or (d)
          your violation of any law or any right of any third party.
        </p>

        <h2 id="warranties">14. Disclaimer of Warranties</h2>

        <p>
          THE SERVICE IS PROVIDED <strong>"AS-IS"</strong> AND{" "}
          <strong>"AS-AVAILABLE,"</strong> WITHOUT WARRANTIES OF ANY KIND,
          WHETHER EXPRESS, IMPLIED, OR STATUTORY. WE DISCLAIM ALL WARRANTIES,
          INCLUDING WITHOUT LIMITATION ANY WARRANTIES OF MERCHANTABILITY,
          FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, ACCURACY,
          RELIABILITY, AND UNINTERRUPTED OR ERROR-FREE OPERATION. WE DO NOT
          WARRANT THAT THE SERVICE WILL MEET YOUR REQUIREMENTS, THAT SUGGESTIONS
          WILL BE ACCURATE OR SECURE, OR THAT THE SERVICE WILL BE AVAILABLE AT
          ANY PARTICULAR TIME OR LOCATION.
        </p>

        <h2 id="liability">15. Limitation of Liability</h2>

        <p>
          <strong>15.1.</strong> TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO
          EVENT WILL CHUNKY TOFU STUDIOS OR ITS AFFILIATES, OFFICERS, DIRECTORS,
          EMPLOYEES, CONTRACTORS, AGENTS, OR LICENSORS BE LIABLE FOR ANY
          INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY, OR PUNITIVE
          DAMAGES, INCLUDING WITHOUT LIMITATION LOST PROFITS, LOST REVENUE, LOST
          DATA, OR BUSINESS INTERRUPTION, ARISING OUT OF OR RELATING TO THESE
          TERMS OR THE SERVICE, REGARDLESS OF THE THEORY OF LIABILITY AND EVEN
          IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
        </p>

        <p>
          <strong>15.2.</strong> TO THE MAXIMUM EXTENT PERMITTED BY LAW, OUR
          TOTAL LIABILITY ARISING OUT OF OR RELATING TO THESE TERMS OR THE
          SERVICE WILL NOT EXCEED THE GREATER OF (A) THE AMOUNTS YOU PAID US FOR
          THE SERVICE IN THE SIX (6) MONTHS PRECEDING THE EVENT GIVING RISE TO
          THE LIABILITY OR (B) ONE HUNDRED U.S. DOLLARS ($100).
        </p>

        <h2 id="disputes">16. Dispute Resolution</h2>

        <p>
          <strong>16.1. Informal Resolution.</strong> Before filing any formal
          claim, you agree to first contact us at{" "}
          <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a> and attempt in
          good faith to resolve the dispute. You and we agree to make a
          good-faith effort to resolve the dispute through informal negotiation
          within sixty (60) days of the date the informal notice is sent.
        </p>

        <p>
          <strong>16.2. Governing Law and Venue.</strong> These Terms and any
          dispute arising out of or relating to these Terms or the Service are
          governed by the laws of the State of New Jersey, without regard to its
          conflict-of-laws principles. Subject to Section 16.1, any action
          arising out of or relating to these Terms will be brought exclusively
          in the state or federal courts located in New Jersey, and you consent
          to the personal jurisdiction of those courts.
        </p>

        <p>
          <strong>16.3. Class Action Waiver.</strong> You and we agree that each
          may bring claims against the other only in your or its individual
          capacity, and not as a plaintiff or class member in any purported
          class or representative proceeding.
        </p>

        <h2 id="misc">17. Miscellaneous</h2>

        <p>
          <strong>17.1. Entire Agreement.</strong> These Terms, together with
          the Privacy Policy and any Order Form or other documents referenced in
          these Terms, constitute the entire agreement between you and us
          regarding the Service and supersede all prior agreements and
          understandings.
        </p>

        <p>
          <strong>17.2. Assignment.</strong> You may not assign these Terms or
          any rights under these Terms without our prior written consent. We may
          freely assign these Terms.
        </p>

        <p>
          <strong>17.3. Severability.</strong> If any provision of these Terms
          is held to be invalid or unenforceable, the remaining provisions will
          remain in full force and effect.
        </p>

        <p>
          <strong>17.4. Waiver.</strong> Our failure to enforce any right or
          provision of these Terms is not a waiver of that right or provision.
        </p>

        <p>
          <strong>17.5. Electronic Communications.</strong> You consent to
          receive communications from us in electronic form, and you agree that
          any electronic communications we provide will satisfy any legal
          requirement that communications be in writing.
        </p>

        <p>
          <strong>17.6. Export Compliance.</strong> You agree to comply with all
          applicable export-control and sanctions laws and regulations in your
          use of the Service.
        </p>

        <p>
          <strong>17.7. No Agency.</strong> Nothing in these Terms creates any
          agency, partnership, joint venture, or employment relationship between
          you and us.
        </p>

        <p>
          <strong>17.8. Contact.</strong> Questions about these Terms can be
          sent to <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>.
        </p>
      </article>
    </div>
  </main>
)
